@echo off 
echo Installation de Microsoft Professionnel Plus 2019 ...
echo ...
echo Get more offers on gitdi.com ...
echo ...
echo Don't Close This Tab (waiting for installation) ...
setup.exe /configure ProPlusVLK2019.xml
echo.
echo Termine.
